### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by SvenHerr** [doxakis/How-to-use-tesseract-ocr-4.0-with-csharp#3]
Hello, 
I downloaded the project and run it and i get this error:

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\SVH\Downloads\How-to-use-tesseract-ocr-4.0-with-csharp-master\How-to-use-tesseract-ocr-4.0-with-csharp-master\Demo\bin\Debug\samples'.'

**Comment by doxakis** [comment]
Hi,

I will check that this weekend.
Can you tell me which IDE/version you used ? (Rider, Visual Studio)

Thanks!

**Comment by SvenHerr** [comment]
Im using Visual Studio

**Comment by doxakis** [comment]
Hi,
I reproduced it also in Visual Studio.
That's strange, it worked in the past.
Anyway, I fix it in 3068f33c39124b2f8c1d402364b348b282da6259.
If it doesn't work for you, you can reopen the issue.
Thanks!
